@echo off
setlocal enabledelayedexpansion
REM Generated by ChatGPT

set totalLines=0

REM Change the path to your repo if needed
set repoPath=.

REM Find all .luau files and count lines
for /r "%repoPath%" %%f in (*.luau) do (
    for /f %%l in ('find /c /v "" ^< "%%f"') do (
        set /a totalLines+=%%l
    )
)

echo Total lines in .luau files: !totalLines!
endlocal