local Themes = {}

Themes.Dark = {
	TextColor = Color3.fromRGB(200, 200, 200),
	
	Background = Color3.fromRGB(47, 47, 47),
	Setting = Color3.fromRGB(57, 57, 57),
	Section = Color3.fromRGB(67, 67, 67),
	Border = Color3.fromRGB(37, 37, 37),
	Hover = Color3.fromRGB(77, 77, 77),
	Hold = Color3.fromRGB(27, 27, 27),
	
	Positive = Color3.fromRGB(0, 170, 255),
}

Themes.Light = {
	TextColor = Color3.fromRGB(40, 40, 40),
	
	Background = Color3.fromRGB(255, 255, 255),
	Setting = Color3.fromRGB(255, 255, 255),
	Section = Color3.fromRGB(230, 230, 230),
	Border = Color3.fromRGB(200, 200, 200),
	Hover = Color3.fromRGB(200, 235, 255),
	Hold = Color3.fromRGB(217, 217, 217),

	Positive = Color3.fromRGB(0, 80, 150),--Color3.fromRGB(0, 170, 255),
}

return Themes
