--disable
--[[
You currently have no elements. Press the plus icon in the top-left corner to create a new byt.

A "byt" is what BytExecutor uses to store code that it can run. Hovering over a byt gives you the primary interactions, such as execute, delete, and others. Double-click in order to edit a byt. A more detailed explanation and guide may be found at the Help option or the associated DevForum post.
]]


--[[
A "byt" is what BytExecutor uses as a container to store code that it can run later. Just think of it as a sort of "Studio Script".
When hovering over an element several icons will pop out to the left. These are the primary interactions that you can click, such as
execute, delete, etc. To edit/access an element, double-click it away from the interaction buttons.

Advanced options can be accessed by right-clicking. Several UI elements have additional features that can only be used this way, such as
creating folders, renaming elements, controlling save data, executing under specific models and more.
Try right-clicking everything! (plus icon, element, execute button, and empty list)
]]